
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app
spec:
  selector:
    matchLabels:
      name: ui-app
  replicas: 1
  template:
    metadata:
      labels:
        name: ui-app
    spec:
      containers:
      - name: ui-app
        image: exastro/epochsampleappui:master.20210708183910
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - containerPort: 443


---
apiVersion: v1
kind: Service
metadata:
  name: ui-app
  labels:
    name: ui-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32001
  selector:
    name: ui-app
